# -*- coding: utf-8 -*-
"""analizar_frecuencia_palabras.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WWnoY5vW6u_rr390QfT97LXL_k3zUZrq
"""

import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

# Inicializar el vectorizador
vectorizer = CountVectorizer(stop_words='english')

def analizar_frecuencia_palabras(df, columna_texto, grupo_columna=None, grupo=None):
    """
    Función para analizar las palabras más comunes en una columna de texto de un DataFrame.

    Parámetros:
    - df: DataFrame con los datos.
    - columna_texto: nombre de la columna que contiene los textos a analizar.
    - grupo_columna: nombre de la columna de grupo (opcional, si se requiere filtrar por un grupo específico).
    - grupo: valor del grupo para filtrar (opcional).

    Retorna:
    - DataFrame con las palabras y su frecuencia, ordenadas de mayor a menor.
    """
    # Filtrar por grupo si se ha especificado
    if grupo_columna and grupo:
        df = df[df[grupo_columna] == grupo]

    # Vectorizar los textos
    X = vectorizer.fit_transform(df[columna_texto])

    # Obtener las palabras más comunes
    palabras = vectorizer.get_feature_names_out()
    frecuencias = X.sum(axis=0).A1  # Sumar las frecuencias de cada palabra

    # Crear un DataFrame con las palabras y sus frecuencias
    palabras_frecuencia = pd.DataFrame(list(zip(palabras, frecuencias)), columns=['Palabra', 'Frecuencia'])

    # Ordenar de mayor a menor frecuencia
    return palabras_frecuencia.sort_values(by='Frecuencia', ascending=False)